<?php

/**
 * @file
 * Contains dkomito_dev_tools.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dkomito_dev_tools_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dkomito_dev_tools module.
    case 'help.page.dkomito_dev_tools':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Various resources helpful for deploying websites and helping with client editors') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dkomito_dev_tools_theme() {
  return [
    'style_compliance_guide' => [
			'variables' => [],
		],
  ];
}